services:
    client:
      build: 
        context: ./client
      ports:
        - "5173:5173"
      volumes:
        - ./client:/app
      environment:
        - NODE_ENV=development
      depends_on:
        - server

    server:
      build: 
        context: ./server
      ports:
        - "8080:8080"
      volumes:
        - ./server:/app
      environment:
        - NODE_ENV=development